### ISSUE TITLE
Kmeans to replace the updated centers?

### ISSUE THREAD

**Issue by Harry-Up** [boyangumn/DCN-New#1]
Hello, I am researching about deep clustering and plan to incorporate this work. 

However, I am confused about why kmeans is used to replace the updated centers in the code (DCN-New/multi_layer_km.py 1121-1146 lines), which is even not appeared in the old version project (DCN). 

Look forward to your reply. Have a good time!

**Comment by boyangumn** [comment]
Hello,

Thank you for your interest.

This is one of the options I explored: doing a kmeans at the end means using our method purely as a representation learning method. This was asked by one reviewer during the conference submission. I remember the results are similar whether or not do the final kmeans. Sorry for the confusion this has brought -- I should have upload the version without the lines you mentioned.

If you have more questions, feel free to contact me via email yang4173@umn.edu. I check emails everyday, but not GitHub notifications. Thank you.
